[alias]
b = "build"
bl = "build --release"

c = "check"

r = "run"
rl = "run --release"

s = "search"
i = "install"

up = "install-update"


[build]
jobs = 14
rustc-wrapper = "/home/bido/.cargo/bin/sccache"
