general {
    before_sleep_cmd = qs ipc call lock activate
    after_sleep_cmd  = hyprctl dispatch dpms on
}

# 3000秒(50分)後にロック
listener {
    timeout    = 3000
    on-timeout = qs ipc call lock activate
    on-resume  = hyprctl dispatch dpms on
}

# ロック後300秒(5分)で画面オフ
listener {
    timeout    = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
    lock       = true
}
