
background {
    color = rgba(0, 0, 0, 1)
}

label {
    text = cmd[update:1000] echo "$(date '+%Y-%m-%d')"
    color = rgba(170, 170, 170, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 96
    halign = center
    valign = center
}

label {
    text = ┌──────────────────────────┐
    color = rgba(170, 170, 170, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 56
    halign = center
    valign = center
}

label {
    text = cmd[update:0] printf "│  login:    %-14s│" "$USER"
    color = rgba(170, 170, 170, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 28
    halign = center
    valign = center
}

label {
    text = │  password:
    color = rgba(170, 170, 170, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = -108, 0
    halign = center
    valign = center
}

label {
    text = │
    color = rgba(170, 170, 170, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 194, 0
    halign = center
    valign = center
}

label {
    text = └──────────────────────────┘
    color = rgba(170, 170, 170, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, -28
    halign = center
    valign = center
}

input-field {
    size = 201, 28
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.35
    dots_center = false
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(170, 170, 170, 1.0)
    font_family = JetBrainsMono Nerd Font
    font_size = 24
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    rounding = 0
    position = 86, 0
    halign = center
    valign = center
    check_color = rgba(170, 170, 170, 1.0)
    fail_color = rgba(255, 85, 85, 1.0)
    fail_text = incorrect ($ATTEMPTS)
    fail_transition = 200
    capslock_color = rgba(255, 255, 100, 1.0)
}
