general {
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 3000秒(50分)後に画面をロック
listener {
    timeout = 3000
    on-timeout = hyprlock
    on-resume = hyprctl dispatch dpms on
}

# ロックされてから300秒(5分)後に画面をオフにする
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
    lock = true
}