
background {
    color = rgba(28, 29, 36, 1)
}

label {
    text = cmd[update:1000] echo "$(date '+%Y-%m-%d')"
    color = rgba(189, 147, 249, 1.0)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    text = $USER
    color = rgba(98, 114, 164, 1.0)
    font_size = 13
    font_family = JetBrainsMono Nerd Font
    position = 0, 30
    halign = center
    valign = center
}

input-field {
    size = 280, 28
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = 0
    outer_color = rgba(98, 114, 164, 1.0)
    inner_color = rgba(40, 42, 54, 1.0)
    font_color = rgba(248, 248, 242, 1.0)
    font_family = JetBrainsMono Nerd Font
    font_size = 13
    fade_on_empty = false
    placeholder_text = password
    hide_input = false
    rounding = 0
    check_color = rgba(80, 250, 123, 1.0)
    fail_color = rgba(255, 85, 85, 1.0)
    fail_text = $FAIL ($ATTEMPTS)
    fail_transition = 200
    capslock_color = rgba(241, 250, 140, 1.0)
}
