# 入力モードインジケーター（"en"/"あ"）のフォントサイズ
TrayFont="Sans Bold 32"

# トレイラベルのアウトラインカラー
TrayOutlineColor=#000000

# トレイラベルのテキストカラー
TrayTextColor=#ffffff

# テキストアイコンを優先
PreferTextIcon=True

# 入力パネルを非表示にする
# Use Per Screen DPI
PerScreenDPI=False

# 候補ウィンドウを非表示（インジケーターは消えるが候補も消える）
# ShowInputMethodInformation=False
